name: PracticeCore
version: '1.0.0'
main: fr.louis.practice.PracticeCore
api-version: 1.8
softdepend: [LuckPerms, AdvancedEnchantments, TownPractice]
authors: [Louis]
description: Core practice moderne avec expérience Kohi/Minemen

commands:
  party:
    description: Gestion des parties
    aliases: [p]
  duel:
    description: Envoyer une demande de duel
  queue:
    description: Rejoindre une queue
    aliases: [q]
  event:
    description: Gestion des events
  stats:
    description: Voir ses statistiques
  leaderboard:
    description: Voir le classement
    aliases: [lb, top]
  spawn:
    description: Retourner au spawn
  spectate:
    description: Spectater un match
    aliases: [spec]
  settings:
    description: Gérer ses paramètres
  kit:
    description: Gestion des kits
  elo:
    description: Voir son ELO
  ping:
    description: Voir son ping
  match:
    description: Informations du match
